apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "metrics.fullname" . }}"
  labels:
    {{- include "metrics.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "metrics.selectorLabels" . | nindent 6 }}